name: application
description: "Unsere Schnitzeljagd App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  cloud_functions: ^6.0.4
  firebase_storage: ^13.0.4

  # Login
  google_sign_in: ^6.2.1

  # Location / Permissions
  geolocator: ^14.0.2
  permission_handler: ^11.3.1

  # UI
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8

  # Maps (OpenStreetMap)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_icon.png

flutter_icons:
  android: true
  ios: false
  image_path: assets/logo_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/logo_icon.png
